# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 941b32bd47093fdf6e026d2441d0c5e674b348438f407c4f2f2c7441c1be2dae2f5046710e1749cec74639cb017afca2fcf08bea512b2fc70b3ddef1c3fbccc8

test:
  secret_key_base: 25f677712f4d5b94a7372600d92e8b6590a2d2239ebb340db0bb82cd50250017404f3a3577a104cca47916a3cc8cbe934e0a2663bb145a22003fc90f32763e7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
